services:
  letters_api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - letters_db
  letters_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: letters
      POSTGRES_PASSWORD: letters
      POSTGRES_DB: lettersdb
    ports:
      - "5432:5432"